services:
  postgres2:
    image: postgres:latest
    container_name: postgres-container2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: excel
    ports:
      - "5433:5432"  # Use a different port to avoid conflict
    volumes:
      - postgres_data2:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - app-network2

  pgadmin2:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"  # Use a different port to avoid conflict
    depends_on:
      - postgres2
    volumes:
      - pgadmin_data2:/var/lib/pgadmin  # Persist pgAdmin settings and registered servers
    networks:
      - app-network2

volumes:
  postgres_data2:
    driver: local  # Volume for PostgreSQL data persistence
  pgadmin_data2:
    driver: local  # Volume for pgAdmin data persistence (settings, registered servers)

networks:
  app-network2:
    driver: bridge
